spring.application.name=verto-shop

# H2 file DB (creates files verto-db.* in project root)
spring.datasource.url=jdbc:h2:file:./verto-db
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA / Hibernate
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# H2 console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console



